apiVersion: v1
kind: Service
metadata:
  name: web-frontend-cluster-ip-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    component: web
  ports:
  - port: 3000
    targetPort: 3000
    name: web-app
